allowBuilds:
  '@prisma/engines': true
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  prisma: true
  sharp: false
  unrs-resolver: false
  workerd: set this to true or false
